name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/dpf-cmake-action.yml
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  # macos:
  #   strategy:
  #     matrix:
  #       target: [macos-universal]
  #   runs-on: macos-11
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: ./.github/workflows/dpf-cmake-action.yml
  #       with:
  #         target: ${{ matrix.target }}
  #         pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/dpf-cmake-action.yml
        with:
          target: ${{ matrix.target }}
          pawpaw: true
          suffix: '-posix'

  # pluginval:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - uses: ./.github/workflows/dpf-cmake-action.yml
  #       with:
  #         target: pluginval
